# Generated by Django 6.0.4 on 2026-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_detalleventa_subtotal_venta_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta Débito'), ('credito', 'Tarjeta Crédito'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
