# Generated by Django 6.0.4 on 2026-04-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_venta_medio_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='INVENTA WEB', max_length=100)),
                ('limite_stock', models.PositiveIntegerField(default=5)),
                ('color_principal', models.CharField(default='#2563eb', max_length=20)),
            ],
        ),
    ]
