# Generated by Django 6.0.4 on 2026-04-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_detallepedidoproveedor_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('fruta', 'Fruta'), ('verdura', 'Verdura'), ('abarrote', 'Abarrote'), ('bebida', 'Bebida'), ('limpieza', 'Limpieza'), ('lacteo', 'Lácteo'), ('panaderia', 'Panadería'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
