# Generated by Django 6.0.4 on 2026-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('fruta', 'Fruta'), ('verdura', 'Verdura'), ('abarrote', 'Abarrote'), ('bebidas', 'Bebidas'), ('limpieza', 'Limpieza'), ('lacteos', 'Lácteos'), ('mascotas', 'Mascotas'), ('panaderia', 'Panadería'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
