# Generated by Django 6.0.4 on 2026-05-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_producto_precio_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('fruta', 'Fruta'), ('verdura', 'Verdura'), ('Abarrote', 'Abarrote'), ('Bebidas', 'Bebidas'), ('Limpieza', 'Limpieza'), ('Lacteos', 'Lacteos'), ('Mascotas', 'Mascotas'), ('panaderia', 'Panadería'), ('Otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
