# Generated by Django 6.0.4 on 2026-05-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='ciudad_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='comuna_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='direccion_empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='giro_empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='rut_empresa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='limite_stock',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='nombre_empresa',
            field=models.CharField(default='Empresa', max_length=100),
        ),
    ]
