# Generated by Django 6.0.4 on 2026-05-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracionsistema_ciudad_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_venta',
            field=models.CharField(choices=[('unidad', 'Por unidad'), ('peso', 'Por peso')], default='unidad', max_length=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
