# Generated by Django 6.0.4 on 2026-06-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_producto_tipo_venta_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('fruta', 'Fruta'), ('verdura', 'Verdura'), ('abarrote', 'Abarrote'), ('bebida', 'Bebida'), ('limpieza', 'Limpieza'), ('lacteo', 'Lácteo'), ('mascotas', 'Mascotas'), ('panaderia', 'Panadería'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
