# Generated by Django 6.0.4 on 2026-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='tema_visual',
            field=models.CharField(choices=[('claro', 'Claro'), ('blanco', 'Blanco limpio'), ('azul', 'Azul suave'), ('verde', 'Verde suave'), ('oscuro', 'Oscuro')], default='claro', max_length=20),
        ),
    ]
