# Generated by Django 6.0.4 on 2026-06-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuracionsistema_tema_visual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tema_visual',
            field=models.CharField(choices=[('claro', 'Claro'), ('arena', 'Arena'), ('azul_corporativo', 'Azul corporativo'), ('verde_bosque', 'Verde bosque'), ('oscuro', 'Oscuro')], default='claro', max_length=30),
        ),
    ]
